name: 'RecipeViewer'
version: "${version}"
api-version: '1.21.4'
bootstrapper: 'io.github.md5sha256.recipeviewer.RecipeViewerBootstrap'
main: 'io.github.md5sha256.recipeviewer.RecipeViewerPlugin'
authors: [ md5sha256 ]
dependencies:
  server:
    Nexo:
      load: BEFORE
      required: false
permissions:
  recipeviewer.base:
    description: "Permission to view the base /recipeviewer command"
    default: op
  recipeviewer.recipe:
    description: "Permission to run /recipeviewer recipe"
    default: op
  recipeviewer.category:
    description: "Permission to run /recipewviewer category"
    default: op
  recipeviewer.reload:
    description: "Permission to run /recipewviewer reload"
    default: op